### PR TITLE
hidaya: bump 1.1

### PR DESCRIPTION
**Pull request by Stunkymonkey**

### CODE REVIEW

**Comment by Stunkymonkey** [comment]
wait a second, i will make a new release, because the current CI is failing

**Comment by bugwelle** [comment]
Let me know when it's ready for review. :)

**Comment by Stunkymonkey** [comment]
ready for merge

**Review by bugwelle — COMMENTED** [review]
- checksum: :heavy_check_mark:
- theme structure: :heavy_check_mark: 

What I would change is to change `http://i.ytimg.com` to `https://i.ytimg.com` in `trailer.js`.

Also: Is `concert_logo_100x25.png` just a one pixel image? Same for all other 100x25 images.

I see that you have multiple authors. It may be nice to have multiple `<author>` tags in the future. I've opened https://github.com/Komet/MediaElch/issues/1364 for that.

Regards,
Andre :)

**Comment by Stunkymonkey** [comment]
> What I would change is to change http://i.ytimg.com to https://i.ytimg.com in trailer.js.

good idea. give me a sec.

> Also: Is concert_logo_100x25.png just a one pixel image? Same for all other 100x25 images.

no idea why. Problem with `mediaelch`? I am not doing anything while exporting. but since I do not have any concerts this is a minor issue for me.

**Comment by Stunkymonkey** [comment]
should be fixed

**Comment by bugwelle** [comment]
> no idea why. Problem with `mediaelch`? I am not doing anything while exporting. but since I do not have any concerts this is a minor issue for me.

I directly looked at the files in the ZIP. :)

This is what I see:
concert_logo_100x25

Nothing is shown (a one pixel image, probably corrupted?)

But if it's not an issue for you, then I'll simply merge this. :)

**Comment by Stunkymonkey** [comment]
oh now i understand. I think they are left over from older development.

**Comment by Stunkymonkey** [comment]
for me the release is good to go. The three empty files will be removed in the future.

**Comment by bugwelle** [comment]
Ah, sorry. Thought your comment indicated that you wanted to update it first. :)

Thank you for your work!

**Comment by bugwelle** [comment]
@Stunkymonkey FYI, I noticed that the "update" button always appears for your theme. Turns out that your ZIP file metadata.xml says it's version 1.0 even though the ZIP is for 1.1

**Comment by Stunkymonkey** [comment]
i forgot that :see_no_evil: . I will release a new version in the next days.

**Pull request merged**
